Repository optimizely/swift-sdk, pull requests merged in 2020-07, with the labels that each got.

#339 refact(getValue): Simplifying getValue by default nil value for jsonPath.
  Sources/Optimizely/OptimizelyJSON.swift
  Tests/OptimizelyTests-APIs/OptimizelyClientTests_OptimizelyJSON.swift
Labels: wip

#342 Removes spell check of md files stage from travis.yml
  .travis.yml
Labels: :robot: 16 hrs

#352 fix: fix tests that failed on FSC
  Sources/Data Model/Audience/SemanticVersion.swift
  Tests/OptimizelyTests-DataModel/SemanticVersionTests.swift
Labels: :robot: 4 hrs
